export type TarotCard={id:string;name:string;meaning:string;love:string;career:string;keywords:string[]};

export const tarotCards:TarotCard[]=[
{id:"the-fool",name:"Deli",meaning:"Yeni bir döngünün eşiğinde cesaret, özgürlük ve bilinmeyene güvenme enerjisi.",love:"Kalbin geçmiş yüklerden sıyrılıp yeni bir deneyime açılabilir.",career:"Yeni bir proje, iş veya yön değişikliği için cesur bir başlangıç.",keywords:["başlangıç","özgürlük","cesaret"]},
{id:"the-magician",name:"Büyücü",meaning:"Elindeki yetenekleri bir araya getirerek istediğin sonucu oluşturma gücü.",love:"Çekim ve iletişim gücün yükseliyor; hislerini açıkça göstermek etkili olabilir.",career:"Becerilerini görünür kılacağın ve inisiyatif alacağın bir dönem.",keywords:["yetenek","irade","yaratıcılık"]},
{id:"the-high-priestess",name:"Başrahibe",meaning:"Sezgi, gizli kalan bilgiler ve henüz zamanı gelmemiş bir gerçeği hissetme.",love:"Söylenmeyen duyguları sezebilirsin; acele hüküm verme.",career:"Perde arkasındaki bilgiyi gözlemlemek sana avantaj sağlayabilir.",keywords:["sezgi","gizem","iç ses"]},
{id:"the-empress",name:"İmparatoriçe",meaning:"Bolluk, üretkenlik, şefkat ve büyümekte olan bir bağ veya proje.",love:"İlişkide sıcaklık ve sahiplenme artabilir; bekarlar için güçlü çekim.",career:"Emek verdiğin bir işin meyvelerini toplama potansiyeli.",keywords:["bolluk","sevgi","üretkenlik"]},
{id:"the-emperor",name:"İmparator",meaning:"Düzen, sınır, sorumluluk ve hayatının kontrolünü yeniden ele alma.",love:"İlişkide güven ve net sınırlar önem kazanıyor.",career:"Otorite, liderlik ve daha sağlam bir kariyer düzeni.",keywords:["düzen","güç","liderlik"]},
{id:"the-hierophant",name:"Aziz",meaning:"Değerler, gelenekler, rehberlik ve doğru bildiğin yolda ilerleme.",love:"İlişkinin adını koymak veya ortak değerleri konuşmak gündeme gelebilir.",career:"Deneyimli birinden destek almak ya da kuralları doğru kullanmak avantajlı.",keywords:["değerler","rehberlik","bağ"]},
{id:"the-lovers",name:"Aşıklar",meaning:"Kalpten gelen seçim, güçlü bağ ve hayatının yönünü etkileyen bir karar.",love:"Duygusal çekim çok güçlü; ancak seçim kadar uyum da önemli.",career:"Değerlerinle kariyer hedeflerini aynı çizgide buluşturma zamanı.",keywords:["aşk","seçim","uyum"]},
{id:"the-chariot",name:"Savaş Arabası",meaning:"Kararlılık, hareket ve iki farklı yönü tek bir hedefte birleştirme.",love:"Duygularını yönettiğinde ilişkide ilerleme sağlayabilirsin.",career:"Hedefine odaklanırsan rekabetçi bir dönemde öne çıkabilirsin.",keywords:["irade","hareket","zafer"]},
{id:"strength",name:"Güç",meaning:"Sertlikten değil sabırdan gelen cesaret, özdenetim ve içsel dayanıklılık.",love:"Sakin ve güvenli yaklaşım, duygusal bir gerilimi yumuşatabilir.",career:"Baskı altında soğukkanlı kalman seni güçlü bir konuma taşıyabilir.",keywords:["sabır","cesaret","denge"]},
{id:"the-hermit",name:"Ermiş",meaning:"İçe dönüş, yalnız kalıp gerçek ihtiyacını fark etme ve derin düşünme.",love:"Bir süre alan ihtiyacı duyabilirsin; bu uzaklaşmak değil netleşmek olabilir.",career:"Kariyer yönünü dış seslerden bağımsız değerlendirmek iyi gelebilir.",keywords:["içe dönüş","bilgelik","arayış"]},
{id:"wheel-of-fortune",name:"Kader Çarkı",meaning:"Değişen koşullar, kapanan bir döngü ve beklenmedik bir fırsat.",love:"İlişki dinamiğinde beklenmedik bir dönüş yaşanabilir.",career:"Şans faktörünün yükseldiği, fırsatların hızlı değişebildiği bir dönem.",keywords:["değişim","döngü","fırsat"]},
{id:"justice",name:"Adalet",meaning:"Denge, sonuçlarla yüzleşme ve karar verirken gerçeğe sadık kalma.",love:"İlişkide karşılıklılık ve dürüstlük test edilebilir.",career:"Emeğinin karşılığını almak ve şartları netleştirmek önem kazanıyor.",keywords:["denge","dürüstlük","karar"]},
{id:"the-hanged-man",name:"Asılan Adam",meaning:"Bekleme, perspektif değiştirme ve zorlamadan önce başka bir açıdan bakma.",love:"Bir ilişkinin yönünü anlamak için biraz zaman kazanmak faydalı olabilir.",career:"Hemen sonuç almak yerine stratejiyi değiştirmek daha doğru olabilir.",keywords:["bekleme","bakış açısı","teslimiyet"]},
{id:"death",name:"Ölüm",meaning:"Fiziksel bir anlam değil; eski bir dönemin kapanması ve güçlü bir dönüşüm.",love:"Seni yoran ilişki biçimi sona erip daha dürüst bir düzen başlayabilir.",career:"Eski çalışma tarzını bırakıp yeni bir sayfaya geçme enerjisi.",keywords:["dönüşüm","kapanış","yenilenme"]},
{id:"temperance",name:"Denge",meaning:"Aşırılıkları yumuşatma, sabır ve iki farklı enerjiyi uyumlandırma.",love:"İlişkide sakinlik ve karşılıklı anlayış bağınızı güçlendirebilir.",career:"Adım adım ilerlemek, aceleci bir hamleden daha verimli sonuç verebilir.",keywords:["denge","sabır","uyum"]},
{id:"the-devil",name:"Şeytan",meaning:"Bağımlılık, güçlü arzu ve seni özgürce hareket etmekten alıkoyan döngüleri fark etme.",love:"Yoğun çekim var; ancak kıskançlık veya kontrol temasını gözlemle.",career:"Para veya başarı hırsının sınırlarını belirlemek önemli.",keywords:["arzu","bağ","gölge"]},
{id:"the-tower",name:"Kule",meaning:"Beklenmedik bir fark edişin eski düzeni sarsması ve gerçeğin görünür olması.",love:"Bir konuşma ilişki hakkında düşündüğünden daha fazla netlik getirebilir.",career:"Plan değişebilir; esnek kaldığında yeni yol daha görünür olur.",keywords:["uyanış","sarsıntı","gerçek"]},
{id:"the-star",name:"Yıldız",meaning:"Umut, iyileşme, ilham ve uzun vadeli bir dileğin yeniden canlanması.",love:"Kalbinin yeniden güvenmeyi öğrenmesi için güzel bir enerji.",career:"Yaratıcılığın ve vizyonun görünürlük kazanabilir.",keywords:["umut","ilham","iyileşme"]},
{id:"the-moon",name:"Ay",meaning:"Belirsizlik, sezgiler ve korkuların gerçeklerle karışabileceği bir dönem.",love:"Karşı tarafın niyetini varsaymak yerine açıkça sormak önemli.",career:"Eksik bilgiyle karar verme; ayrıntıları yeniden kontrol et.",keywords:["sezgi","belirsizlik","rüya"]},
{id:"the-sun",name:"Güneş",meaning:"Açıklık, neşe, başarı ve saklı kalan bir konunun aydınlanması.",love:"Sıcaklık ve dürüstlük duygusal hayatı canlandırabilir.",career:"Başarı, görünürlük ve emeğinin fark edilmesi öne çıkıyor.",keywords:["başarı","neşe","aydınlık"]},
{id:"judgement",name:"Mahkeme",meaning:"Uyanış, geçmişi değerlendirme ve artık ertelenemeyen bir karar.",love:"Geçmiş bir bağla ilgili son bir değerlendirme veya yeniden konuşma olabilir.",career:"Geride bıraktığın bir yeteneği tekrar kullanma fırsatı doğabilir.",keywords:["uyanış","karar","yeniden doğuş"]},
{id:"the-world",name:"Dünya",meaning:"Bir döngünün tamamlanması, sonuç alma ve yeni seviyeye geçiş.",love:"Bir ilişkinin önemli bir aşaması tamamlanıp daha olgun bir bağ kurulabilir.",career:"Uzun süredir verdiğin emeğin sonucunu alma ve ufkunu büyütme zamanı.",keywords:["tamamlanma","başarı","bütünlük"]}
];
