"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Bell, BriefcaseBusiness, ChevronRight, Coffee, Crown, Heart, History, Home as HomeIcon, Menu, MessageCircle, Moon, Sparkles, Star, UserRound, WalletCards, X } from "lucide-react";

const discoveries = [
  { title: "Tarot", subtitle: "Kartların bugün ne söylüyor?", href: "/fal/tarot", image: "/fortune/tarot.svg" },
  { title: "Aşk Falı", subtitle: "Kalbindeki sorulara ışık tut.", href: "/fal/ask", image: "/fortune/love.svg" },
  { title: "Para & Bolluk", subtitle: "Maddi enerjini keşfet.", href: "/fal/para", image: "/fortune/money.svg" },
  { title: "Kariyer", subtitle: "İş ve hedeflerin için açılım.", href: "/fal/kariyer", image: "/fortune/career.svg" },
  { title: "Günlük Fal", subtitle: "Bugünün enerjisini keşfet.", href: "/fal/gunluk", image: "/fortune/daily.svg" },
  { title: "Doğum Haritam", subtitle: "Kendini gökyüzünde tanı.", href: "/fal/burc", image: "/fortune/astrology.svg" },
  { title: "Rüya Yorumu", subtitle: "Rüyalarının sembollerini çöz.", href: "/fal/ruya", image: "/fortune/dream.svg" },
  { title: "Numeroloji", subtitle: "Sayıların sana ne söylüyor?", href: "/fal/focus", image: "/fortune/numerology.svg" },
];

export default function Home() {
  const [name, setName] = useState("Dostum");
  const [menuOpen, setMenuOpen] = useState(false);

  useEffect(() => {
    const raw = window.localStorage.getItem("fal-kosesi-profile");
    if (!raw) return;
    try {
      const profile = JSON.parse(raw) as { name?: string };
      if (profile.name?.trim()) setName(profile.name.trim());
    } catch {
      // Keep the neutral fallback greeting if the saved profile is malformed.
    }
  }, []);

  const firstName = name.split(" ")[0] || "Dostum";

  return (
    <main className="min-h-screen bg-[#070714] pb-24 text-white selection:bg-[#e7bd68] selection:text-[#160f1b]">
      <div className="fixed inset-0 -z-10 bg-[radial-gradient(circle_at_20%_0%,rgba(107,61,151,.28),transparent_30%),radial-gradient(circle_at_100%_20%,rgba(201,118,72,.16),transparent_28%),linear-gradient(180deg,#0b0a1b_0%,#070714_55%,#05050d_100%)]" />

      <header className="sticky top-0 z-40 border-b border-white/[.06] bg-[#080817]/80 backdrop-blur-2xl">
        <div className="mx-auto flex h-[68px] max-w-[1180px] items-center justify-between px-4 sm:px-6">
          <button type="button" onClick={() => setMenuOpen(true)} className="grid h-11 w-11 place-items-center rounded-2xl border border-white/10 bg-white/[.04] text-[#f5d78e] transition hover:bg-white/[.08]" aria-label="Menüyü aç"><Menu className="h-5 w-5" /></button>
          <Link href="/" className="flex items-center gap-2.5"><div className="grid h-10 w-10 place-items-center rounded-full border border-[#f0cf80]/30 bg-[#f0cf80]/10 shadow-[0_0_30px_rgba(240,207,128,.1)]"><Moon className="h-5 w-5 fill-[#f6d98f] text-[#f6d98f]" /></div><div className="leading-none"><div className="font-serif text-[19px] font-bold tracking-tight text-[#f6dda2]">Fal Köşesi</div><div className="mt-1 text-[9px] uppercase tracking-[.24em] text-[#aaa1bd]">Kaderini keşfet</div></div></Link>
          <div className="flex items-center gap-2"><button type="button" className="relative grid h-11 w-11 place-items-center rounded-2xl border border-white/10 bg-white/[.04] text-[#f5d78e]" aria-label="Bildirimler"><Bell className="h-5 w-5" /><span className="absolute right-2.5 top-2.5 h-1.5 w-1.5 rounded-full bg-[#f2b84b] shadow-[0_0_10px_#f2b84b]" /></button><Link href="/profil" className="hidden items-center gap-2 rounded-full border border-[#f0cf80]/15 bg-white/[.04] py-1.5 pl-1.5 pr-3 sm:flex"><div className="grid h-8 w-8 place-items-center rounded-full bg-gradient-to-br from-[#f4d998] to-[#93602f] text-[#1a1020]"><UserRound className="h-4 w-4" /></div><span className="max-w-[100px] truncate text-xs font-semibold text-[#eee5d5]">{firstName}</span></Link></div>
        </div>
      </header>

      <div className="mx-auto max-w-[1180px] px-4 sm:px-6">
        <section className="relative mt-4 overflow-hidden rounded-[28px] border border-[#d7b56d]/15 shadow-[0_30px_90px_rgba(0,0,0,.42)] sm:mt-6 sm:rounded-[34px]"><Image src="/fortune/hero.svg" alt="Fal Köşesi mistik kahve falı" fill priority sizes="(max-width: 768px) 100vw, 1180px" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-[#090918]/95 via-[#0b0919]/70 to-[#0b0919]/20" /><div className="relative min-h-[330px] px-6 py-8 sm:min-h-[390px] sm:px-10 sm:py-12 lg:px-14"><div className="max-w-[650px]"><div className="inline-flex items-center gap-2 rounded-full border border-[#f5d88e]/20 bg-black/20 px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[.22em] text-[#f5d88e] backdrop-blur-md"><Sparkles className="h-3.5 w-3.5" /> Sana özel fal köşen</div><h1 className="mt-5 font-serif text-[38px] font-bold leading-[.98] tracking-[-.04em] text-white sm:text-5xl lg:text-6xl">Merhaba {firstName} <span className="text-[#f5d88e]">✦</span></h1><p className="mt-4 max-w-[560px] text-base leading-7 text-[#d9d1e1] sm:text-lg">Bugün senin için neler söylüyor?</p><p className="mt-2 font-serif text-sm italic text-[#c8b9d6] sm:text-base">“Her fincan, yeni bir hikâye anlatır…”</p></div></div></section>

        <section className="relative mt-5 overflow-hidden rounded-[26px] border border-[#a56fff]/25 bg-[#17132b]/90 p-3 shadow-[0_22px_65px_rgba(0,0,0,.34)] sm:mt-6 sm:p-4"><div className="grid gap-4 md:grid-cols-[190px_1fr_220px] md:items-center"><div className="relative h-[155px] overflow-hidden rounded-[20px] bg-[#0d0a18] sm:h-[175px]"><Image src="/fortune/hero.svg" alt="Kahve falı" fill sizes="220px" className="object-cover object-[70%_65%]" /><div className="absolute inset-0 bg-gradient-to-t from-[#0b0815] via-transparent to-transparent" /><div className="absolute bottom-3 left-3 rounded-full border border-white/10 bg-black/45 px-2.5 py-1 text-[10px] font-semibold text-[#f6d98e] backdrop-blur-md">AI ANALİZ</div></div><div className="px-1 sm:px-2"><div className="flex items-center gap-2 text-[#f6d98e]"><Coffee className="h-5 w-5" /><span className="text-xs font-bold uppercase tracking-[.2em]">Kahve Falı</span></div><h2 className="mt-2 font-serif text-2xl font-bold text-white sm:text-3xl">Fincanını gönder, sembollerini keşfet.</h2><p className="mt-2 max-w-xl text-sm leading-6 text-[#bdb4c9]">Fincan ve tabak fotoğrafını yükle. Sana özel, detaylı ve sıcak bir yorum hazırlayalım.</p><Link href="/fal/upload" className="mt-4 inline-flex items-center justify-center gap-2 rounded-full bg-gradient-to-r from-[#f6d88e] via-[#efbd69] to-[#c76e9a] px-6 py-3 text-sm font-black text-[#1b1020] shadow-[0_12px_30px_rgba(236,178,107,.22)] transition hover:-translate-y-0.5">Falımı Yorumla <ChevronRight className="h-4 w-4" /></Link></div><div className="grid gap-2 md:pr-1"><Link href="/fal/upload" className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[.045] p-3 transition hover:bg-white/[.08]"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#f3d48b]/10 text-[#f3d48b]"><Coffee className="h-5 w-5" /></span><span><b className="block text-sm">Fincan Fotoğrafı</b><small className="text-xs text-[#aaa1bb]">Yüklemeye hazır</small></span></Link><Link href="/fal/upload" className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[.045] p-3 transition hover:bg-white/[.08]"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#a875ff]/10 text-[#bd92ff]"><Star className="h-5 w-5" /></span><span><b className="block text-sm">Tabak Fotoğrafı</b><small className="text-xs text-[#aaa1bb]">Daha detaylı analiz</small></span></Link></div></div></section>

        <section className="mt-9 sm:mt-12"><div className="mb-4 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.28em] text-[#f0c978]">✦ keşfet</p><h2 className="mt-1 font-serif text-3xl font-bold tracking-tight">Bugün neye bakmak istersin?</h2></div><Link href="/fal/burc" className="hidden items-center gap-1 text-sm font-semibold text-[#d7cce1] sm:flex">Tümünü Gör <ChevronRight className="h-4 w-4" /></Link></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{discoveries.map((item) => <Link key={item.title} href={item.href} className="group overflow-hidden rounded-[20px] border border-white/[.09] bg-[#111022] shadow-[0_12px_35px_rgba(0,0,0,.25)] transition duration-300 hover:-translate-y-1 hover:border-[#d5a6ff]/35 hover:shadow-[0_18px_45px_rgba(0,0,0,.4)]"><div className="relative aspect-[1.45] overflow-hidden"><Image src={item.image} alt={item.title} fill sizes="(max-width: 640px) 50vw, (max-width: 1024px) 33vw, 25vw" className="object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-[#111022] via-transparent to-transparent opacity-85" /></div><div className="relative -mt-8 px-4 pb-4"><h3 className="font-serif text-lg font-bold text-white sm:text-xl">{item.title}</h3><p className="mt-1 line-clamp-2 text-xs leading-5 text-[#bcb3c9]">{item.subtitle}</p></div></Link>)}</div></section>

        <Link href="/fal/premium" className="group mt-8 flex items-center gap-4 overflow-hidden rounded-[24px] border border-[#e8c86f]/40 bg-[radial-gradient(circle_at_0%_50%,rgba(242,193,93,.28),transparent_35%),linear-gradient(100deg,#211827,#17121e)] p-5 shadow-[0_20px_50px_rgba(0,0,0,.3)] transition hover:border-[#f5d98f]/65 sm:mt-10 sm:p-6"><div className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-gradient-to-br from-[#ffe49c] to-[#c7863e] text-[#20121b] shadow-[0_10px_35px_rgba(238,193,96,.25)]"><Crown className="h-7 w-7" /></div><div className="min-w-0 flex-1"><p className="font-serif text-lg font-bold sm:text-xl">Premium ile daha fazlasını keşfet</p><p className="mt-1 text-xs leading-5 text-[#bfb3c4] sm:text-sm">Sınırsız fal, detaylı yorumlar ve kişiselleştirilmiş içerikler seni bekliyor.</p></div><span className="hidden shrink-0 items-center gap-1 rounded-full bg-[#f4d18b] px-5 py-3 text-sm font-black text-[#24161c] sm:inline-flex">Premium’a Geç <ChevronRight className="h-4 w-4" /></span></Link>

        <section className="mt-9 sm:mt-12"><div className="mb-4 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.28em] text-[#a9a0b9]">geçmiş</p><h2 className="mt-1 font-serif text-2xl font-bold">Son Falın</h2></div><Link href="/fal/gecmis" className="flex items-center gap-1 text-sm text-[#c9bfd2]">Tüm Geçmişim <ChevronRight className="h-4 w-4" /></Link></div><div className="flex items-center gap-4 rounded-[22px] border border-white/[.09] bg-[#101021]/80 p-3 sm:p-4"><div className="relative h-20 w-20 shrink-0 overflow-hidden rounded-2xl border border-white/10"><Image src="/fortune/hero.svg" alt="Son kahve falı" fill sizes="80px" className="object-cover object-[70%_70%]" /></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2 text-xs text-[#e8cf91]"><Coffee className="h-4 w-4" /> Kahve Falı <span className="text-[#777184]">• Son falın</span></div><h3 className="mt-1 font-semibold">Fincanındaki sembollere yeniden bak</h3><p className="mt-1 truncate text-xs text-[#9890a3]">Falını aç ve Falcıya Sor ile devam et.</p></div><Link href="/fal/gecmis" className="hidden items-center gap-1 rounded-full border border-[#a86cff]/45 px-4 py-2.5 text-xs font-bold text-[#d4b8ff] sm:flex">Yorumu Gör <ChevronRight className="h-4 w-4" /></Link></div></section>
      </div>

      <nav className="fixed bottom-0 left-0 right-0 z-50 border-t border-white/[.08] bg-[#090918]/95 px-2 pb-[max(8px,env(safe-area-inset-bottom))] pt-2 backdrop-blur-2xl"><div className="mx-auto grid max-w-[720px] grid-cols-5">{[["Ana Sayfa", "/", HomeIcon],["Fal Geçmişim", "/fal/gecmis", History],["Favorilerim", "/favoriler", Heart],["Falcıya Sor", "/fal/ask", MessageCircle],["Premium", "/fal/premium", Crown]].map(([label, href, Icon]) => <Link key={String(label)} href={String(href)} className="flex min-h-[58px] flex-col items-center justify-center gap-1 rounded-2xl text-[#9f97ae] transition hover:bg-white/[.04] hover:text-[#f4d68e]"><Icon className="h-5 w-5" /><span className="text-[9px] font-semibold sm:text-[10px]">{label as string}</span></Link>)}</div></nav>

      {menuOpen && <div className="fixed inset-0 z-[60] bg-black/65 backdrop-blur-sm" onClick={() => setMenuOpen(false)}><aside className="h-full w-[86%] max-w-[360px] border-r border-white/10 bg-[#0c0b1b] p-5 shadow-[30px_0_90px_rgba(0,0,0,.5)]" onClick={(event) => event.stopPropagation()}><div className="flex items-center justify-between"><div className="font-serif text-2xl font-bold text-[#f4d68e]">Fal Köşesi</div><button type="button" onClick={() => setMenuOpen(false)} className="grid h-10 w-10 place-items-center rounded-xl bg-white/[.05]"><X className="h-5 w-5" /></button></div><p className="mt-2 text-sm text-[#9991a8]">Merhaba {firstName}, hangi keşfe çıkıyoruz?</p><div className="mt-8 grid gap-2">{[["Kahve Falı", "/fal/upload", Coffee],["Tarot", "/fal/tarot", Sparkles],["Aşk Falı", "/fal/ask", Heart],["Para & Bolluk", "/fal/para", WalletCards],["Kariyer", "/fal/kariyer", BriefcaseBusiness],["Günlük Fal", "/fal/gunluk", Moon],["Doğum Haritam", "/fal/burc", Star]].map(([label, href, Icon]) => <Link key={String(label)} href={String(href)} onClick={() => setMenuOpen(false)} className="flex items-center gap-3 rounded-2xl border border-white/[.06] bg-white/[.03] p-3.5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#f1d38b]/10 text-[#f1d38b]"><Icon className="h-5 w-5" /></span><span className="font-semibold">{label as string}</span><ChevronRight className="ml-auto h-4 w-4 text-[#746d7e]" /></Link>)}</div><Link href="/fal/premium" onClick={() => setMenuOpen(false)} className="mt-6 flex items-center gap-3 rounded-2xl border border-[#e9c66d]/35 bg-[#e9c66d]/10 p-4 text-[#f5d992]"><Crown className="h-5 w-5" /><span className="font-bold">Premium’u Keşfet</span></Link></aside></div>}
    </main>
  );
}
